services:
  web-testing:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - db-testing
    environment:
      - CONTAINER_ROLE=web
      - DATABASE_URL=postgresql://user:password@db-testing:5432/mydatabase
      - FLASK_APP=app.py
      - WEB_NAME=web
      - PORT=5001
      - TESTING=true
    networks:
      - main_network

  db-testing:
    image: postgres:latest
    command: ["postgres", "-c", "max_connections=100","-c","shared_buffers=8096MB","-c","work_mem=256MB"]
    volumes:
      - /mnt/data/db-testing:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - main_network

  alembic-testing:
    build: 
      context: .
      dockerfile: Dockerfile.alembic
    volumes:
      - .:/app
    depends_on:
      - db-testing
    environment:
      - DATABASE_URL=postgresql://user:password@db-testing:5432/mydatabase
      - FLASK_APP=app.py
      - PORT=5001
      - WEB_NAME=web
      - REDIS_NAME=redis
      - TESTING=true
    networks:
      - main_network

  #no nginx or certbot; relies on main docker-compose.prod.yml


volumes:
  postgres_data:
  redis-data:

networks:
  main_network:
    driver: bridge
    external: true
