"""automigrate

Revision ID: 38115bc6b317
Revises: e055ced7f5fb
Create Date: 2024-05-30 21:05:22.815230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38115bc6b317'
down_revision: Union[str, None] = 'e055ced7f5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #create column and set default to avoid nulls
    op.add_column('user', sa.Column('send_admin_notifications', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_admin_notifications')
    # ### end Alembic commands ###
