"""automigrate

Revision ID: 5fcee6b02afc
Revises: eb5130566f5e
Create Date: 2024-05-22 21:01:59.290853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcee6b02afc'
down_revision: Union[str, None] = 'eb5130566f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('button_request', sa.Column('email_sent_timestamp', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('button_request', 'email_sent_timestamp')
    # ### end Alembic commands ###
