"""automigrate

Revision ID: cabebe42f7fa
Revises: 38115bc6b317
Create Date: 2024-06-28 19:00:39.176376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = 'cabebe42f7fa'
down_revision: Union[str, None] = '38115bc6b317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'button_request', ['id'])
    op.drop_constraint('product_admin_options_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'admin_options_id')
    op.add_column('user', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires_at', sa.Float(), nullable=True))
    op.alter_column('user', 'send_admin_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###
def downgrade():
    pass