"""automigrate

Revision ID: eb5130566f5e
Revises: 2b3730c2c2fd
Create Date: 2024-05-09 02:58:32.811474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb5130566f5e'
down_revision: Union[str, None] = '2b3730c2c2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folders', sa.JSON(), nullable=False),
    sa.Column('admin_options_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_options_id'], ['admin_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'admin_options', ['id'])
    op.drop_column('admin_options', 'project_types')
    op.create_unique_constraint(None, 'button_request', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'button_request', type_='unique')
    op.add_column('admin_options', sa.Column('project_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_options', type_='unique')
    op.drop_table('product')
    # ### end Alembic commands ###
